#!/bin/bash
set -e
wp --path=/var/www/keys-starter.com --allow-root wc product create --name="Win 11 IoT Ent LTSC 2024 High End" --slug=win-11-iot-2024-high-end --type=simple --status=publish --regular_price=16000 --catalog_visibility=visible --short_description="IoT Enterprise LTSC 2024 - High End edition" --user=1 2>&1
wp --path=/var/www/keys-starter.com --allow-root wc product create --name="Win 11 IoT Ent LTSC 2024 Value" --slug=win-11-iot-2024-value --type=simple --status=publish --regular_price=8500 --catalog_visibility=visible --short_description="IoT Enterprise LTSC 2024 - Value edition" --user=1 2>&1
wp --path=/var/www/keys-starter.com --allow-root wc product create --name="Win 10 IoT Ent 2021 LTSC High End" --slug=win-10-iot-2021-high-end --type=simple --status=publish --regular_price=16000 --catalog_visibility=visible --short_description="IoT Enterprise LTSC 2021 - High End edition" --user=1 2>&1
wp --path=/var/www/keys-starter.com --allow-root wc product create --name="Win 10 IoT Ent 2021 LTSC Value" --slug=win-10-iot-2021-value --type=simple --status=publish --regular_price=8500 --catalog_visibility=visible --short_description="IoT Enterprise LTSC 2021 - Value edition" --user=1 2>&1
wp --path=/var/www/keys-starter.com --allow-root wc product create --name="Win 11 IoT Ent MultiLang OLC High End" --slug=win-11-iot-ml-high-end --type=simple --status=publish --regular_price=16000 --catalog_visibility=visible --short_description="IoT Enterprise MultiLang - High End" --user=1 2>&1
wp --path=/var/www/keys-starter.com --allow-root wc product create --name="Win 11 IoT Ent MultiLang OLC Value" --slug=win-11-iot-ml-value --type=simple --status=publish --regular_price=8500 --catalog_visibility=visible --short_description="IoT Enterprise MultiLang - Value" --user=1 2>&1
wp --path=/var/www/keys-starter.com --allow-root wc product create --name="Win 11 IoT Ent MultiLang OLC Entry" --slug=win-11-iot-ml-entry --type=simple --status=publish --regular_price=4500 --catalog_visibility=visible --short_description="IoT Enterprise MultiLang - Entry" --user=1 2>&1
wp --path=/var/www/keys-starter.com --allow-root wc product create --name="Win 10 IoT Ent 2019 LTSC High End" --slug=win-10-iot-2019-high-end --type=simple --status=publish --regular_price=16000 --catalog_visibility=visible --short_description="IoT Enterprise LTSC 2019 - High End edition" --user=1 2>&1
wp --path=/var/www/keys-starter.com --allow-root wc product create --name="Win 10 IoT Ent 2019 LTSC Value" --slug=win-10-iot-2019-value --type=simple --status=publish --regular_price=8500 --catalog_visibility=visible --short_description="IoT Enterprise LTSC 2019 - Value edition" --user=1 2>&1
wp --path=/var/www/keys-starter.com --allow-root wc product create --name="Win Svr IoT Std 2025 16 Core" --slug=win-svr-iot-2025 --type=simple --status=publish --regular_price=94400 --catalog_visibility=visible --short_description="Windows Server IoT 2025 Standard - 16 Core" --user=1 2>&1
wp --path=/var/www/keys-starter.com --allow-root wc product create --name="Win Svr IoT Std 2022 16 Core" --slug=win-svr-iot-2022 --type=simple --status=publish --regular_price=85000 --catalog_visibility=visible --short_description="Windows Server IoT 2022 Standard - 16 Core" --user=1 2>&1
wp --path=/var/www/keys-starter.com --allow-root wc product create --name="Win Svr IoT Std 2019 16 Core" --slug=win-svr-iot-2019 --type=simple --status=publish --regular_price=78900 --catalog_visibility=visible --short_description="Windows Server IoT 2019 Standard - 16 Core" --user=1 2>&1
wp --path=/var/www/keys-starter.com --allow-root wc product create --name="SQL Svr Std RUNTIME 2019 IoT 1 Clt" --slug=sql-svr-2019-runtime --type=simple --status=publish --regular_price=18900 --catalog_visibility=visible --short_description="SQL Server Standard RUNTIME 2019 IoT - 1 Client" --user=1 2>&1
wp --path=/var/www/keys-starter.com --allow-root wc product create --name="SQL Svr Std RUNTIME 2022 IoT 1 Clt" --slug=sql-svr-2022-runtime --type=simple --status=publish --regular_price=22900 --catalog_visibility=visible --short_description="SQL Server Standard RUNTIME 2022 IoT - 1 Client" --user=1 2>&1
echo ALL 14 DONE