export const products = [
  {slug:"windows-10-pro", n:"Windows 10 Professional", p:13.08, c:"#0078D4", d:"Genuine Microsoft Windows 10 Pro digital license key. Lifetime activation, multi-language support.",
   specs:{version:"Windows 10 Pro",platform:"PC / 64-bit",lang:"Multi-language",activation:"Digital License",type:"Retail / OEM",support:"Lifetime"}},
  {slug:"windows-11-pro", n:"Windows 11 Professional", p:14.09, c:"#0078D4", d:"Latest Microsoft Windows 11 Pro license. Enhanced security, modern UI, Copilot ready.",
   specs:{version:"Windows 11 Pro",platform:"PC / 64-bit",lang:"Multi-language",activation:"Digital License",type:"Retail / OEM",support:"Lifetime"}},
  {slug:"office-2021-pro", n:"Office 2021 Professional Plus", p:24.09, c:"#D83B01", d:"Full Microsoft Office 2021 suite: Word, Excel, PowerPoint, Outlook, Access, Publisher.",
   specs:{version:"Office 2021 Pro Plus",platform:"Windows PC",lang:"English",activation:"Digital License",type:"Retail",support:"Lifetime"}},
  {slug:"win10-office-bundle", n:"Windows 10 Pro + Office 2021 Bundle", p:30.09, c:"#0078D4", d:"Best value bundle. Windows 10 Pro + Office 2021 Professional Plus at a discounted price.",
   specs:{version:"Win10 Pro + Office 2021",platform:"PC / 64-bit",lang:"Multi-language",activation:"Digital License",type:"Bundle",support:"Lifetime"}},
  {slug:"win-svr-2019", n:"Windows Server 2019", p:9.09, c:"#005A9E", d:"Microsoft Windows Server 2019 Standard edition. Reliable enterprise server OS.",
   specs:{version:"Server 2019 Standard",platform:"Server / 64-bit",lang:"English",activation:"Digital License",type:"Retail",support:"Lifetime"}},
  {slug:"win-svr-2022", n:"Windows Server 2022", p:11.09, c:"#005A9E", d:"Latest Microsoft Windows Server 2022. Advanced security, hybrid capabilities.",
   specs:{version:"Server 2022 Standard",platform:"Server / 64-bit",lang:"English",activation:"Digital License",type:"Retail",support:"Lifetime"}},
  {slug:"office-2019-pro", n:"Office 2019 Professional Plus", p:19.09, c:"#D83B01", d:"Microsoft Office 2019 Pro Plus. Classic productivity suite for professionals.",
   specs:{version:"Office 2019 Pro Plus",platform:"Windows PC",lang:"English",activation:"Digital License",type:"Retail",support:"Lifetime"}},
  {slug:"office-2016-pro", n:"Office 2016 Professional Plus", p:14.09, c:"#D83B01", d:"Office 2016 Professional Plus. Full suite for PC. Proven reliability.",
   specs:{version:"Office 2016 Pro Plus",platform:"Windows PC",lang:"English",activation:"Digital License",type:"Retail",support:"Lifetime"}},
  {slug:"office-2024-pro", n:"Office 2024 Professional Plus", p:8.09, c:"#D83B01", d:"Newest Office 2024 Pro Plus. Latest features and enhanced collaboration.",
   specs:{version:"Office 2024 Pro Plus",platform:"Windows PC",lang:"English",activation:"Digital License",type:"Retail",support:"Lifetime"}},
  {slug:"project-2021-pro", n:"Project Professional 2021", p:15.09, c:"#217346", d:"Microsoft Project Professional 2021. Advanced project management tool.",
   specs:{version:"Project 2021 Pro",platform:"Windows PC",lang:"English",activation:"Digital License",type:"Retail",support:"Lifetime"}},
  {slug:"visio-2021-pro", n:"Visio Professional 2021", p:15.09, c:"#5C2E91", d:"Microsoft Visio Professional 2021. Professional diagramming and flowcharting.",
   specs:{version:"Visio 2021 Pro",platform:"Windows PC",lang:"English",activation:"Digital License",type:"Retail",support:"Lifetime"}},
  {slug:"exchange-server", n:"Exchange Server 2019", p:9.09, c:"#0072C6", d:"Microsoft Exchange Server 2019 Standard. Enterprise email and calendaring.",
   specs:{version:"Exchange 2019 Std",platform:"Server",lang:"English",activation:"Digital License",type:"Retail",support:"Lifetime"}},
  {slug:"sql-server", n:"SQL Server 2019 Standard", p:9.09, c:"#CC2927", d:"Microsoft SQL Server 2019 Standard. Powerful database management system.",
   specs:{version:"SQL Server 2019 Std",platform:"Server",lang:"English",activation:"Digital License",type:"Retail",support:"Lifetime"}},
  {slug:"win11-office-bundle", n:"Windows 11 Pro + Office 2021 Bundle", p:34.09, c:"#0078D4", d:"Premium bundle. Windows 11 Pro + Office 2021 Professional Plus.",
   specs:{version:"Win11 Pro + Office 2021",platform:"PC / 64-bit",lang:"Multi-language",activation:"Digital License",type:"Bundle",support:"Lifetime"}},
  {slug:"win11-pro-2pc", n:"Windows 11 Pro 2PC", p:26.09, c:"#0078D4", d:"Windows 11 Pro license for 2 PCs. Perfect for home + work setup.",
   specs:{version:"Win11 Pro 2PC",platform:"2 PCs / 64-bit",lang:"Multi-language",activation:"Digital License",type:"Multi-PC",support:"Lifetime"}},
  {slug:"win10-pro-2pc", n:"Windows 10 Pro 2PC", p:24.09, c:"#0078D4", d:"Windows 10 Pro license for 2 PCs. Great value for dual device users.",
   specs:{version:"Win10 Pro 2PC",platform:"2 PCs / 64-bit",lang:"Multi-language",activation:"Digital License",type:"Multi-PC",support:"Lifetime"}},
  {slug:"win11-office-visio-bundle", n:"Win11 Pro + Office + Visio Bundle", p:45.09, c:"#0078D4", d:"Ultimate bundle. Windows 11 Pro + Office 2021 + Visio 2021 Professional.",
   specs:{version:"Win11+Office+Visio",platform:"PC / 64-bit",lang:"Multi-language",activation:"Digital License",type:"Bundle",support:"Lifetime"}},
  {slug:"svr2019-office-bundle", n:"Server 2019 + Office 2021 Bundle", p:29.09, c:"#005A9E", d:"Server + productivity bundle. Windows Server 2019 + Office 2021 Professional Plus.",
   specs:{version:"Svr2019 + Office 2021",platform:"Server + PC",lang:"English",activation:"Digital License",type:"Bundle",support:"Lifetime"}},
  {slug:"office-visio-bundle", n:"Office 2021 + Visio 2021 Bundle", p:34.09, c:"#D83B01", d:"Professional bundle. Office 2021 Pro Plus + Visio 2021 Professional.",
   specs:{version:"Office + Visio 2021",platform:"Windows PC",lang:"English",activation:"Digital License",type:"Bundle",support:"Lifetime"}}
];