import { PRODUCT_IMAGES } from "../data/product-images";
import VARIANTS from "../data/image-variants.json";

// PSI phase 1: responsive card images. Variants (-320w/-640w.webp) are
// generated by scripts/build-image-variants.py and indexed in
// src/data/image-variants.json; the original file always remains the fallback.
const CARD_SIZES = "(max-width: 768px) 45vw, 300px";

function srcSet(src: string): string | undefined {
  const widths = VARIANTS[src as keyof typeof VARIANTS] as number[] | undefined;
  if (!widths || !widths.length) return undefined;
  const stem = src.replace(/\.webp$/, "");
  return [
    ...widths.map((w) => `${stem}-${w}w.webp ${w}w`),
    `${src} ${widths[widths.length - 1] + 1}w`,
  ].join(", ");
}

export default function ProductImage({ slug, name, className = "", eager = false }: { slug: string; name: string; className?: string; eager?: boolean }) {
  const src = PRODUCT_IMAGES[slug] || "";
  if (!src) {
    return (
      <div className={"w-full aspect-[4/3] rounded-xl bg-gradient-to-br from-[#7c3aed]/10 to-[#6d28d9]/10 flex items-center justify-center overflow-hidden " + className}>
        <span className="text-5xl font-bold text-[#7c3aed]/25">{name ? name[0] : "K"}</span>
      </div>
    );
  }
  const set = srcSet(src);
  return (
    <div className={"w-full aspect-[4/3] rounded-xl overflow-hidden bg-white border border-[#e8e8ed] flex items-center justify-center " + className}>
      <img src={src} alt={name} className="w-full h-full object-contain p-3" loading={eager ? "eager" : "lazy"} fetchPriority={eager ? "high" : "auto"} srcSet={set} sizes={set ? CARD_SIZES : undefined} />
    </div>
  );
}
